# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430', max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slogan1', models.CharField(max_length=40, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d1')),
                ('slogan2', models.CharField(max_length=40, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d2')),
                ('slogan3', models.CharField(max_length=40, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d3')),
                ('about', models.CharField(max_length=100, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431\u043e \u043c\u043d\u0435')),
            ],
        ),
    ]
