# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='slogan4',
            field=models.CharField(default='\u0421\u043b\u043e\u0433\u0430\u043d4', max_length=250, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d3'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='about',
            field=models.CharField(max_length=300, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e\u0431\u043e \u043c\u043d\u0435'),
        ),
    ]
