# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0002_auto_20170919_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='slogan4',
            field=models.CharField(default='\u0421\u043b\u043e\u0433\u0430\u043d4', max_length=250, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d4'),
        ),
    ]
