# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0003_auto_20170919_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442\u044b', max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('text', models.CharField(max_length=40, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('foto', models.ImageField(null=True, upload_to='works', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
        ),
    ]
