# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0006_auto_20170922_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': '\u041e\u0431\u043e \u043c\u043d\u0435 \u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u041e\u0431\u043e \u043c\u043d\u0435 \u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u041e\u0442\u0437\u044b\u0432\u044b \u0437\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u043e\u0432 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e\u0442\u0437\u044b\u0432\u044b', 'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b \u0437\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u043e\u0432 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e\u0442\u0437\u044b\u0432\u044b'},
        ),
        migrations.AlterModelOptions(
            name='mainpageworks',
            options={'verbose_name': '\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442 \u0438 \u0444\u043e\u0442\u043e \u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 + \u0413\u0430\u043b\u0435\u0440\u0435\u044f', 'verbose_name_plural': '\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442 \u0438 \u0444\u043e\u0442\u043e \u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 + \u0413\u0430\u043b\u0435\u0440\u0435\u044f'},
        ),
    ]
