# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0007_auto_20170922_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
