# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0437\u0438\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
    ]
