# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0010_comment_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=100, verbose_name='\u0410\u043a\u0446\u0438\u044f')),
                ('text', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('foto', models.ImageField(null=True, upload_to='discount', verbose_name='\u0424\u043e\u0442\u043e_\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0410\u043a\u0446\u0438\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0430\u043a\u0446\u0438\u0438',
                'verbose_name_plural': '\u0410\u043a\u0446\u0438\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0430\u043a\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='\u0422\u0435\u043c\u0430')),
                ('text', models.TextField(verbose_name='\u0421\u0442\u0430\u0442\u044c\u044f')),
                ('foto', models.ImageField(null=True, upload_to='interest', verbose_name='\u0424\u043e\u0442\u043e_\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u044b\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u043e\u0435',
                'verbose_name_plural': '\u0418\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u044b\u0435 \u0441\u0442\u0430\u0442\u044c\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u043e\u0435',
            },
        ),
    ]
