# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0011_discount_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='foto',
            field=models.ImageField(default=None, null=True, upload_to='discount', verbose_name='\u0424\u043e\u0442\u043e_\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
