# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0013_auto_20170924_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0420\u0430\u0431\u043e\u0442')),
                ('text', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='\u0426\u0435\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0440\u0435\u0447\u0435\u043d\u044c \u0440\u0430\u0431\u043e\u0442 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0420\u0430\u0431\u043e\u0442\u044b',
                'verbose_name_plural': '\u041f\u0435\u0440\u0435\u0447\u0435\u043d\u044c \u0440\u0430\u0431\u043e\u0442 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0420\u0430\u0431\u043e\u0442\u044b',
            },
        ),
    ]
