# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0016_auto_20170925_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quanty',
            field=models.CharField(default='\u0448\u0442.', max_length=30, verbose_name='\u0412\u0435\u043b\u0438\u0447\u0438\u043d\u0430 \u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u041e\u0431\u044a\u0435\u043c'),
        ),
    ]
