# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0019_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b'},
        ),
    ]
