# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0020_auto_20170927_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u041e\u0431\u043e \u043c\u043d\u0435', max_length=20, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slogan1', models.TextField(max_length=100, verbose_name='\u0421\u043e \u043c\u043d\u043e\u0439 \u0432\u044b\u0433\u043e\u0434\u043d\u043e')),
                ('slogan2', models.TextField(max_length=100, verbose_name='\u0427\u0442\u043e \u043f\u043e\u043b\u0443\u0447\u0430\u0435\u0442\u0435')),
                ('slogan3', models.TextField(max_length=100, verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0432\u0435\u043d\u043d\u044b\u0439 \u043f\u043e\u0434\u0445\u043e\u0434')),
                ('about', models.TextField(max_length=300, verbose_name='\u041e\u0431\u043e \u043c\u043d\u0435 - \u043a\u0440\u0430\u0442\u043a\u043e')),
            ],
            options={
                'verbose_name': '\u041e\u0431\u043e \u043c\u043d\u0435 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u041e\u0431\u043e \u043c\u043d\u0435',
                'verbose_name_plural': '\u041e\u0431\u043e \u043c\u043d\u0435 \u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u041e\u0431\u043e \u043c\u043d\u0435',
            },
        ),
    ]
