# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santeh', '0021_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(max_length=500, verbose_name='\u041e\u0431\u043e \u043c\u043d\u0435 - \u043a\u0440\u0430\u0442\u043a\u043e'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slogan1',
            field=models.TextField(max_length=200, verbose_name='\u0421\u043e \u043c\u043d\u043e\u0439 \u0432\u044b\u0433\u043e\u0434\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slogan2',
            field=models.TextField(max_length=200, verbose_name='\u0427\u0442\u043e \u043f\u043e\u043b\u0443\u0447\u0430\u0435\u0442\u0435'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slogan3',
            field=models.TextField(max_length=200, verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0432\u0435\u043d\u043d\u044b\u0439 \u043f\u043e\u0434\u0445\u043e\u0434'),
        ),
    ]
