# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='text2',
            field=models.TextField(verbose_name='Остальное'),
        ),
    ]
