# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20170511_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='name1',
            field=models.CharField(default='Название', max_length=20, verbose_name='Обо мне'),
        ),
    ]
