# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_aboutme_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='name1',
        ),
    ]
