# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_remove_aboutme_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='name',
            field=models.CharField(default='Главная', max_length=20, verbose_name='Название'),
        ),
    ]
