# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_aboutme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Учеба', max_length=20, verbose_name='Название')),
                ('year', models.PositiveIntegerField(default=1, verbose_name='Год')),
                ('place', models.CharField(max_length=50, verbose_name='Учебное заведение')),
                ('edu', models.CharField(max_length=50, verbose_name='Тип образования')),
            ],
        ),
    ]
