# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0006_mylearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Работа', max_length=20, verbose_name='Название')),
                ('year_on', models.PositiveIntegerField(default=1, verbose_name='Год начала работы')),
                ('year_off', models.PositiveIntegerField(default=1, verbose_name='Год окончания работы')),
                ('jobname', models.CharField(max_length=50, verbose_name='Название фирмы')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('site', models.URLField(max_length=50, verbose_name='Сайт фирмы')),
            ],
        ),
    ]
