# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0007_myjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobs',
            name='position',
            field=models.CharField(default='занимаемая должность', max_length=50, verbose_name='Должность'),
        ),
    ]
