# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0008_myjobs_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjobs',
            name='jobname',
            field=models.CharField(max_length=80, verbose_name='Название фирмы'),
        ),
    ]
