# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0009_auto_20170511_1415'),
    ]

    operations = [
    ]
