# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0010_auto_20170512_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Организация', max_length=20, verbose_name='Название')),
                ('town', models.CharField(max_length=80, verbose_name='Город')),
                ('org_name', models.CharField(max_length=80, verbose_name='Название фирмы')),
                ('site', models.URLField(max_length=50, verbose_name='Сайт фирмы')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('desc', models.TextField(verbose_name='Описание деятельности')),
            ],
        ),
    ]
