# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0011_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobs',
            name='orgname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutme.Organizations', verbose_name='Организация'),
        ),
    ]
