# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0012_myjobs_orgname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myjobs',
            name='jobname',
        ),
        migrations.RemoveField(
            model_name='myjobs',
            name='site',
        ),
    ]
