# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0013_auto_20170514_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='name',
        ),
    ]
