# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0014_remove_organizations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='name',
            field=models.CharField(default='Организация', max_length=20, verbose_name='Название'),
        ),
    ]
