# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0016_organizations_sert'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobs',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Отобразить на сайте'),
        ),
    ]
