# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\u0417\u0430\u043f\u0438\u0441\u044c', 'verbose_name_plural': '\u0417\u0430\u043f\u0438\u0441\u0438'},
        ),
    ]
