# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170407_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=15, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
    ]
