# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Главная', max_length=20, verbose_name='Название')),
                ('text', models.TextField(verbose_name='О мотоциклах')),
            ],
        ),
    ]
