# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название марки')),
                ('description', models.TextField(blank=True, verbose_name='Описание марки')),
            ],
        ),
        migrations.CreateModel(
            name='Revw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
                ('author', models.CharField(default='admin', max_length=15, verbose_name='Автор')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsite.Mark')),
            ],
        ),
    ]
