# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsite', '0002_mark_revw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revw',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Фото'),
        ),
    ]
