# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsite', '0004_auto_20170525_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
                ('image', models.ImageField(blank=True, upload_to='img', verbose_name='Фото')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsite.Mark')),
            ],
        ),
    ]
